CC:=g++
CXX:=g++
DEBUG=DEBUG
OUTPUTNAME:=riser
OUTPATH=output
ROOT=./include/
INCLUDES += -I$(ROOT) -I/usr/include/ -L./lib/

LDFLAGS += -lpthread -levent ./lib/libleveldb.a
CPPFLAGS += -fPIC -pg -Wall

objects := $(patsubst %.cpp,%.o,$(wildcard *.cpp))

.PHONY: all clean
all: $(OBJNAME)

%.o:%.cpp
	$(CXX) $(CPPFLAGS) -c $< -o $@ $(INCLUDES) -D$(DEBUG)

clean:
	-rm -f $(OUTPUTNAME) $(objects)
