hw := $(shell sh -c './gent_hw.sh')
CC:=g++
CXX:=g++
OUTPUTNAME:=riser-server
OUTPATH=output
ROOT=./include/
INCLUDES += -I$(ROOT) -I/usr/include/ -L./lib/

LDFLAGS +=-lpthread -levent ./lib/libleveldb.a
CPPFLAGS += -fPIC -Wall
OS := $(shell uname -s)
IS_DARWIN := $(shell echo $(OS)|grep -i Darwin)
ifdef IS_DARWIN
LDFLAGS += -D_DARWIN
endif

objects := $(patsubst %.cpp,%.o,$(wildcard *.cpp))

.PHONY: all clean
all: $(OBJNAME)

%.o:%.cpp
	$(CXX) $(CPPFLAGS) -c $< -o $@ $(INCLUDES) 

clean:
	-rm -f $(OUTPUTNAME) $(objects)
